// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	di "github.com/kuetix/container"
	"github.com/kuetix/engine/engine/defines"
	"github.com/kuetix/engine/engine/workflow"
	transitionsApiAuth "github.com/kuetix/std-auth/modules/api/auth/transitions"
)

func init() {
	di.Boot()
	di.DependencyInjection["api/auth"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"api/auth"+"/"+"jwt", func() interface{} {
			return workflow.ServiceTransitionMapping{ServiceName: name, Name: "jwt", Impl: transitionsApiAuth.NewJWTTransitions()}
		})
		di.ToResolve(defines.TransitionPrefix+"api/auth"+"/"+"user", func() interface{} {
			return workflow.ServiceTransitionMapping{ServiceName: name, Name: "user", Impl: transitionsApiAuth.NewUserTransitions()}
		})
	}
}
