// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	di "github.com/kuetix/container"
	"github.com/kuetix/engine/engine/defines"
	"github.com/kuetix/engine/engine/workflow"
	transitionsAuth "github.com/kuetix/std-auth/modules/auth/transitions"
)

func init() {
	di.Boot()
	di.DependencyInjection["auth"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"auth"+"/"+"bff", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "bff", Impl: transitionsAuth.NewBFFTransitions() }})
		di.ToResolve(defines.TransitionPrefix+"auth"+"/"+"jwt", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "jwt", Impl: transitionsAuth.NewJWTTransitions() }})
		di.ToResolve(defines.TransitionPrefix+"auth"+"/"+"mfa", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "mfa", Impl: transitionsAuth.NewMFATransitions() }})
		di.ToResolve(defines.TransitionPrefix+"auth"+"/"+"password", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "password", Impl: transitionsAuth.NewUserTransitions() }})
	}
}
