// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	"github.com/kuetix/engine/boot"
	"github.com/kuetix/engine/engine/domain/interfaces"
)

func init() {
	boot.AddMetaFunctionCache(map[string]map[string]map[string]interfaces.FunctionMetadata{
		"auth": {
			"jwt": {
				"GetToken": {
					Name:        "GetToken",
					NumIn:       1,
					NumOut:      1,
					ArgTypes:    []string{"string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"authHeader"},
					ReturnNames: []string{"r"},
				},
				"GenerateToken": {
					Name:        "GenerateToken",
					NumIn:       4,
					NumOut:      1,
					ArgTypes:    []string{"string", "string", "string", "int"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"userID", "username", "email", "expiresInHours"},
					ReturnNames: []string{"r"},
				},
				"ValidateToken": {
					Name:        "ValidateToken",
					NumIn:       1,
					NumOut:      1,
					ArgTypes:    []string{"string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"tokenString"},
					ReturnNames: []string{"r"},
				},
				"RefreshToken": {
					Name:        "RefreshToken",
					NumIn:       2,
					NumOut:      1,
					ArgTypes:    []string{"string", "int"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"tokenString", "expiresInHours"},
					ReturnNames: []string{"r"},
				},
				"ExtractTokenFromHeader": {
					Name:        "ExtractTokenFromHeader",
					NumIn:       1,
					NumOut:      1,
					ArgTypes:    []string{"string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"authHeader"},
					ReturnNames: []string{"r"},
				},
			},
			"password": {
				"HashPassword": {
					Name:        "HashPassword",
					NumIn:       2,
					NumOut:      1,
					ArgTypes:    []string{"string", "int"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"password", "min"},
					ReturnNames: []string{"r"},
				},
				"ComparePassword": {
					Name:        "ComparePassword",
					NumIn:       2,
					NumOut:      1,
					ArgTypes:    []string{"string", "string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"password", "passwordHash"},
					ReturnNames: []string{"r"},
				},
				"ResetPassword": {
					Name:        "ResetPassword",
					NumIn:       3,
					NumOut:      1,
					ArgTypes:    []string{"string", "string", "string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"email", "newPassword", "requestingUserEmail"},
					ReturnNames: []string{"r"},
				},
				"RequestPasswordReset": {
					Name:        "RequestPasswordReset",
					NumIn:       1,
					NumOut:      1,
					ArgTypes:    []string{"string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"email"},
					ReturnNames: []string{"r"},
				},
			},
		},
	})
}
