// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	"github.com/kuetix/engine/boot"
	"github.com/kuetix/engine/pkg/domain/interfaces"
)

func init() {
	boot.AddMetaFunctionCache(map[string]map[string]map[string]interfaces.FunctionMetadata{
		"api/auth": {
			"jwt": {
				"ValidateToken": {
					Name:        "ValidateToken",
					NumIn:       1,
					NumOut:      1,
					ArgTypes:    []string{"string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"tokenString"},
					ReturnNames: []string{"r"},
				},
				"RefreshToken": {
					Name:        "RefreshToken",
					NumIn:       2,
					NumOut:      1,
					ArgTypes:    []string{"string", "int"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"tokenString", "expiresInHours"},
					ReturnNames: []string{"r"},
				},
				"ExtractTokenFromHeader": {
					Name:        "ExtractTokenFromHeader",
					NumIn:       1,
					NumOut:      1,
					ArgTypes:    []string{"string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"authHeader"},
					ReturnNames: []string{"r"},
				},
				"GetToken": {
					Name:        "GetToken",
					NumIn:       1,
					NumOut:      1,
					ArgTypes:    []string{"string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"authHeader"},
					ReturnNames: []string{"r"},
				},
				"GenerateToken": {
					Name:        "GenerateToken",
					NumIn:       4,
					NumOut:      1,
					ArgTypes:    []string{"string", "string", "string", "int"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"userID", "username", "email", "expiresInHours"},
					ReturnNames: []string{"r"},
				},
			},
			"user": {
				"UpdateIndex": {
					Name:        "UpdateIndex",
					NumIn:       2,
					NumOut:      1,
					ArgTypes:    []string{"string", "string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"email", "otherId"},
					ReturnNames: []string{"r"},
				},
				"LookupID": {
					Name:        "LookupID",
					NumIn:       2,
					NumOut:      1,
					ArgTypes:    []string{"string", "string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"key", "email"},
					ReturnNames: []string{"r"},
				},
				"GetUserByEmail": {
					Name:        "GetUserByEmail",
					NumIn:       1,
					NumOut:      1,
					ArgTypes:    []string{"string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"email"},
					ReturnNames: []string{"r"},
				},
				"ResetPassword": {
					Name:        "ResetPassword",
					NumIn:       3,
					NumOut:      1,
					ArgTypes:    []string{"string", "string", "string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"email", "newPassword", "requestingUserEmail"},
					ReturnNames: []string{"r"},
				},
				"Register": {
					Name:        "Register",
					NumIn:       2,
					NumOut:      1,
					ArgTypes:    []string{"string", "string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"email", "password"},
					ReturnNames: []string{"r"},
				},
				"Login": {
					Name:        "Login",
					NumIn:       2,
					NumOut:      1,
					ArgTypes:    []string{"string", "string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"login", "password"},
					ReturnNames: []string{"r"},
				},
				"GetAllUsers": {
					Name:        "GetAllUsers",
					NumIn:       0,
					NumOut:      1,
					ArgTypes:    []string{},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{},
					ReturnNames: []string{"r"},
				},
				"RequestPasswordReset": {
					Name:        "RequestPasswordReset",
					NumIn:       1,
					NumOut:      1,
					ArgTypes:    []string{"string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"email"},
					ReturnNames: []string{"r"},
				},
			},
		},
	})
}
